using ProcessManager.Domain.Enums;

namespace ProcessManager.Domain.Entities;

/// <summary>
/// A tracked corrective or improvement action generated by a quality event
/// (NonConformance, MRB decision, RCA, PFMEA, audit finding, or management review).
/// Also supports manually created ad-hoc actions.
/// </summary>
public class ActionItem : BaseEntity
{
    /// <summary>Concise statement of what must be done.</summary>
    public string Title { get; set; } = "";

    /// <summary>Full detail and context for the action.</summary>
    public string? Description { get; set; }

    // ── Assignment ───────────────────────────────────────────────────────────

    /// <summary>Identity user ID of the person responsible for completing this action.</summary>
    public string AssignedToUserId { get; set; } = "";

    /// <summary>Display name of the assignee — denormalised for read performance.</summary>
    public string AssignedToDisplayName { get; set; } = "";

    /// <summary>Identity user ID of the person who raised/assigned this action.</summary>
    public string AssignedByUserId { get; set; } = "";

    /// <summary>Display name of the assigner — denormalised for read performance.</summary>
    public string AssignedByDisplayName { get; set; } = "";

    // ── Scheduling ───────────────────────────────────────────────────────────

    public DateTime DueDate { get; set; }

    public ActionItemPriority Priority { get; set; } = ActionItemPriority.Medium;
    public ActionItemStatus Status { get; set; } = ActionItemStatus.Open;

    // ── Source linkage ───────────────────────────────────────────────────────

    public ActionItemSourceType SourceType { get; set; } = ActionItemSourceType.Manual;

    /// <summary>
    /// The ID of the source entity that generated this action (nullable for Manual items).
    /// Resolves against the table indicated by SourceType.
    /// </summary>
    public Guid? SourceEntityId { get; set; }

    // ── Completion ───────────────────────────────────────────────────────────

    public string? CompletedBy { get; set; }
    public DateTime? CompletedAt { get; set; }
    public string? CompletionNotes { get; set; }

    // ── Verification ─────────────────────────────────────────────────────────

    /// <summary>
    /// A different person from the assignee confirms adequate closure.
    /// Two-step closure requirement prevents self-certification.
    /// </summary>
    public string? VerifiedBy { get; set; }
    public DateTime? VerifiedAt { get; set; }
}
